---

- hosts: localhost
  tasks:
    - name: remove redundant packages
      apt:
          autoremove: yes
          force_apt_get: yes

    - name: display post install message
      debug:
        msg:
          - 'Manual steps left to do:'
          - '- git clone the dotfiles repo (optional)'
          - '- add noatime option for your SSD mounts points in /etc/fstab (optional)'
          - '- enable WebRender in firefox; about:config in address bar, then manually set the gfx.webrender.enabled or gfx.webrender.all pref to true (optional)'
          - '- cache in RAM only in firefox: about:config, browser.cache.disk.enable -> false, browser.cache.memory.enable -> true, browser.cache.memory.capacity -> 1048576, browser.cache.memory.max_entry_size -> 51200, check about:cache (optional)'
          - '- Set us-de-vim as default keyboard layout to be loaded at startup'
          - '- Reboot your system'

...
