---

- hosts: localhost
  tasks:
    - name: remove redundant packages
      apt:
          autoremove: yes
          force_apt_get: yes

    - name: display post install message
      debug:
        msg:
          - 'Manual steps left to do:'
          - '- git clone the dotfiles repo (optional)'
          - '- Set us-de-vim as default keyboard layout to be loaded at startup'
          - '- Reboot your system'
          

...
