---
- name: perform a dist upgrade
  apt:
    update_cache: yes
    upgrade: dist
    force_apt_get: yes

- name: install developer tools
  apt:
    name: "{{ base_developer_tools }}"
    state: present
    force_apt_get: yes

- name: create .ssh dir
  file:
    path: "~{{ local_username }}/.ssh"
    state: directory
    mode: '0700'
  become: yes
  become_user: "{{ local_username }}"

- name: install media packages
  apt:
    name: "{{ base_media_tools }}"
    state: present
    force_apt_get: yes

- name: install virtualization tools
  apt:
    name: "{{ base_virtualization_tools }}"
    state: present
    force_apt_get: yes

# add user to docker group to run docker commands without sudo
# add user to vboxusers group so that user can attach usb devices to guest OS
- name: add user to docker and vboxusers groups
  user:
    name: "{{ local_username }}"
    append: yes
    groups:
      - docker
      - vboxusers

# make fstrim run daily rather than the default weekly schedule for SSD longevity
- block:
    - name: enable fstrim.timer
      systemd:
        name: fstrim.timer
        state: started
        enabled: yes

    - name: create systemd fstrim.timer override dir
      file:
        path: /etc/systemd/system/fstrim.timer.d
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: create override.conf file for fstrim.timer
      copy:
        src: etc/systemd/system/fstrim.timer.d/override.conf
        dest: /etc/systemd/system/fstrim.timer.d/override.conf
        owner: root
        group: root
        mode: 0644

    - name: force systemd to reread configs
      systemd:
        daemon_reload: yes

- name: set chromium as default browser
  command: xdg-settings set default-web-browser chromium-browser.desktop

  # disable pulse audio auto mic boost (see https://nzeid.net/pulseaudio-disable-auto-volume)
- block:
    - name: backup alsamixer settings
      command: 'cp -vR /usr/share/pulseaudio/alsa-mixer/paths /usr/share/pulseaudio/alsa-mixer/paths_backup'
    - name: disable auto mic boost
      command: 'perl -pi -0 -e "s/(\[[A-Za-z ]*Mic Boost\][A-Za-z._=\s-]+volume *= *)merge/\1zero/g;" /usr/share/pulseaudio/alsa-mixer/paths/*'

- name: automatically log in
  when: active_directory == false
  blockinfile:
    path: /etc/gdm3/custom.conf
    insertafter: '^#  AutomaticLogin ='
    block: |
      AutomaticLoginEnable = true
      AutomaticLogin = {{ local_username }}

# lsusb | grep "Logitech" for vendor and product number 
- name: disable logitech webcam autofocus when plugging in
  copy:
    src: 99-local-webcam.rules
    dest: /etc/udev/rules.d
   
...
