---

- name: install vscode
  community.general.snap:
    name: code
    classic: yes

- name: install some popular vscode extensions
  command: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"
  become: yes
  become_user: "{{ local_username }}"

- name: install intellij-idea ultimate
  community.general.snap:
    name: intellij-idea-ultimate
    classic: yes

...
